#pytorch_model:
#  obj: kedex.contrib.ops.pytorch_ops.ModuleSequential
#  modules:
#
#    - obj: torchvision.models.resnet._resnet
#      arch: resnet9
#      block:
#        obj: torchvision.models.resnet.BasicBlock
#      layers: [1, 1, 1, 1]
#      pretrained: False
#      progress:  # None
#      num_classes: 199
#
#    - obj: torch.nn.Dropout
#      p: 0.5
#
#    - obj: torch.nn.Linear
#      in_features: 199
#      out_features: 205  # 199 + 2 + 2 + 2
#
#    - obj: kedex.contrib.ops.pytorch_ops.TensorUnsqueeze
#      dim: 1
#
#    - obj: torch.nn.AvgPool1d
#      kernel_size: 3
#      stride: 1
#      padding: 0
#
#    - obj: torch.nn.AvgPool1d
#      kernel_size: 3
#      stride: 1
#      padding: 0
#
#    - obj: torch.nn.AvgPool1d
#      kernel_size: 3
#      stride: 1
#      padding: 0
#
#    - obj: kedex.contrib.ops.pytorch_ops.TensorSqueeze
#      dim: 1
#
#    - obj: torch.nn.Sigmoid
#      _:  # dummy


pytorch_model:
  obj: kedex.ModuleSequential
  modules:

#    - obj: torch.nn.Dropout2d
#      p: 0.5

    - obj: torch.nn.Conv2d  # (15, 30, 60) -> (32, 26, 46)
      in_channels: 15
      out_channels: 32
      kernel_size:
        obj: tuple
        arg:
          - 5
          - 15

    - obj: torch.nn.CELU
      alpha: 1.0
#    - obj: torch.nn.ReLU
#      _:  # dummy

#    - obj: torchvision.models.resnet.BasicBlock
#      inplanes: 8
#      planes: 8

    - obj: torch.nn.Conv2d  # (40, 26, 46) -> (48, 22, 32)
      in_channels: 32
      out_channels: 48
      kernel_size:
        obj: tuple
        arg:
          - 5
          - 15

    - obj: torch.nn.CELU
      alpha: 1.0
#    - obj: torch.nn.ReLU
#      _:  # dummy

#    - obj: torchvision.models.resnet.BasicBlock
#      inplanes: 16
#      planes: 16

    - obj: torch.nn.Conv2d  # (48, 22, 32) -> (56, 18, 18)
      in_channels: 48
      out_channels: 56
      kernel_size:
        obj: tuple
        arg:
          - 5
          - 15

    - obj: torch.nn.CELU
      alpha: 1.0
#    - obj: torch.nn.ReLU
#      _:  # dummy

#    - obj: torchvision.models.resnet.BasicBlock
#      inplanes: 24
#      planes: 24

    - obj: torch.nn.Conv2d  # (56, 18, 18) -> (64, 14, 4)
      in_channels: 56
      out_channels: 64
      kernel_size:
        obj: tuple
        arg:
          - 5
          - 15

    - obj: torch.nn.CELU
      alpha: 1.0
#    - obj: torch.nn.ReLU
#      _:  # dummy

#    - obj: torchvision.models.resnet.BasicBlock
#      inplanes: 32
#      planes: 32

    - obj: torch.nn.Conv2d  # (64, 14, 4) -> (72, 10, 1)
      in_channels: 64
      out_channels: 72
      kernel_size:
        obj: tuple
        arg:
          - 5
          - 4

    - obj: torch.nn.CELU
      alpha: 1.0
#    - obj: torch.nn.ReLU
#      _:  # dummy

    - obj: kedex.TensorFlatten
      _:  # dummy

#    - obj: torch.nn.Dropout
#      p: 0.2

    - obj: torch.nn.Linear
      in_features: 720
      out_features: 205  # 199 + 2 + 2 + 2

    - obj: kedex.TensorUnsqueeze
      dim: 1

    - obj: torch.nn.AvgPool1d
      kernel_size: 3
      stride: 1
      padding: 0

    - obj: torch.nn.AvgPool1d
      kernel_size: 3
      stride: 1
      padding: 0

    - obj: torch.nn.AvgPool1d
      kernel_size: 3
      stride: 1
      padding: 0

    - obj: kedex.TensorSqueeze
      dim: 1

    - obj: torch.nn.Sigmoid
      _:  # dummy


augmentation:
  random_horizontal_flip:
    p: 0
  random_horizontal_shift:
    p: 0
    max_shift: 0

train_batch_size: 64

train_params:
  epochs: 1000  # number of epochs to train
  time_limit: 32400
  early_stopping_params:
    metric: loss
    minimize: True
    patience: 1000
  scheduler:
    obj: ignite.contrib.handlers.param_scheduler.LinearCyclicalScheduler
#    obj: ignite.contrib.handlers.param_scheduler.CosineAnnealingScheduler
  scheduler_params:
    param_name: lr
    start_value:
      obj: mul
      arg:
        - 0.000_000_01
        - obj: train_batch_size
    end_value:
      obj: mul
      arg:
        - 0.000_005
        - obj: train_batch_size
    cycle_epochs: 2  # cycle_size: int(cycle_epochs * len(train_loader))
    cycle_mult: 1.0
    start_value_mult: 1.0
    end_value_mult: 1.0
    save_history: False
  optimizer:
    obj: torch.optim.Adam
#  optimizer:
#    obj: torch.optim.SGD
  optimizer_params:
#    lr:  # learning rate
#      obj: truediv
#      arg:
#        - obj: train_batch_size
#        - 1000
#    momentum:
#      obj: sub
#      arg:
#        - 1
#        - obj: truediv
#          arg:
#            - obj: train_batch_size
#            - 2000
    weight_decay:
      obj: truediv
      arg:
        - 0.001
        - obj: train_batch_size
  loss_fn:
    obj: kaggle_nfl.kaggle_nfl.NflCrpsLossFunc
    min: -4 # -15
    max: 29 # 25
  metrics:
    loss:
      obj: ignite.metrics.Loss
      loss_fn:
        obj: kaggle_nfl.kaggle_nfl.nfl_crps_loss
  train_data_loader_params:
    batch_size:
      obj: train_batch_size
    num_workers: 1
  val_data_loader_params:
    batch_size:
     obj: train_batch_size
    num_workers: 1
  evaluate_train_data: COMPLETED
  evaluate_val_data: EPOCH_COMPLETED
  progress_update: True
  seed: 0  #


RUN_CONFIG:
  tags: # None
  runner: SequentialRunner # None
  node_names: # None
  from_nodes: # None
  to_nodes: # None
  from_inputs: # None
  load_versions: # None
  pipeline_name: __default__

MLFLOW_LOGGING_CONFIG:
  offset_hours: 8
  logging_artifacts:  # None
  
PIPELINES:
  __default__:
    obj: kedex.pipeline.KedexPipeline
    parameters_in_inputs: True
    module: kaggle_nfl.kaggle_nfl
    decorator: kedex.contrib.decorators.log_time
    nodes:

      - inputs: train
#        func:
#          - obj: kedex.df_sample
#            frac: 0.1
#            random_state: 191024
#            col_sample: PlayId
        outputs: df_020

      - inputs: df_020
        func:
          - preprocess
        outputs: df_030

      - inputs: df_030
        outputs: describe

      - inputs: df_030
        func:
          obj: kedex.df_query
          expr: 'PlayerCategory == 0'
        outputs: describe_cat0

      - inputs: df_030
        func:
          obj: kedex.df_query
          expr: 'PlayerCategory == 1'
        outputs: describe_cat1

      - inputs: df_030
        func:
          obj: kedex.df_query
          expr: 'PlayerCategory == 2'
        outputs: describe_cat2

      - inputs: df_030
        func:
          obj: kedex.df_sample
          frac: 0.5
          random_state: 191024
          col_sample: PlayId
          col_assign: Validation
        outputs: df_040

#      - inputs: df_040
#        func: fit_base_model
#        outputs: base_model
#
#      - inputs: base_model
#        func: infer
#        outputs: infered_first_iter
#
#      - inputs: df_030
#        func:
#          obj: kedex.df_sample
#          frac: 0.01
#          random_state: 191024
#          col_sample: PlayId
#        outputs: df_031
#
#      - inputs: df_030
#        outputs: describe

      - inputs: parameters
        func:
          obj: pass_func
          arg:
            obj: pytorch_model
        outputs: initial_model

      - inputs: df_040
        func: generate_datasets
        outputs:
          - train_dataset
          - val_dataset

      - inputs:
          - initial_model
          - train_dataset
          - val_dataset
        func:
          obj: kedex.neural_network_train
          train_params:
            obj: train_params
        outputs: pytorch_model

      - inputs: pytorch_model
        func: infer
        outputs: infered_first_iter
