outcome_col: Yards


RUN_CONFIG:
  tags: # None
  runner: SequentialRunner # None
  node_names: # None
  from_nodes: # None
  to_nodes: # None
  from_inputs: # None
  load_versions: # None
  pipeline_name: __default__

MLFLOW_LOGGING_CONFIG:
  offset_hours: 0
  logging_artifacts:  # None
  
PIPELINES:
  __default__:
    obj: kedex.pipeline.KedexPipeline
    parameters_in_inputs: True
    module: kaggle_nfl.kaggle_nfl
    decorator: kedex.contrib.decorators.log_time
    nodes:

#      - inputs: train
#        func:
#          obj: kedex.df_sample
#          frac: 0.01
#          random_state: 0
#          col_sample: GameId
#        outputs: df_010_samp

#      - inputs: train
#        func:
#          obj: kedex.df_query
#          expr: "Position == 'RB'"
#        outputs: df_020_RB

#      - inputs: df_020_RB
#        outputs: pairplot

      - inputs: train
        func: preprocess
        outputs: df_030

      - inputs: df_030
        func:
          obj: kedex.df_sample
          frac: 0.1
          random_state: 191024
          col_sample: PlayId
          col_assign: Validation
        outputs: df_040

      - inputs: df_040
        func: fit_base_model
        outputs: base_model

      - inputs: base_model
        func: infer
        outputs: infered_first_iter

      - inputs: df_030
        func:
          obj: kedex.df_sample
          frac: 0.01
          random_state: 191024
          col_sample: PlayId
        outputs: df_031

      - inputs: df_030
        outputs: describe


